### ISSUE TITLE
Mod Menu, Xaero's Mods, Inventory Profiles Next, Inventory Sorting, Inventory Management, Inventory Tabs, and Iris GUI compat

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/prideGUI#7]
We should add comaptibility to those mods in PrideGUI. They're mainly just a few textures so it shouldn't be much of a hassle.

Links:
[Mod Menu](https://modrinth.com/mod/modmenu)
[Xaero's Minimap](https://modrinth.com/mod/xaeros-minimap)
[Xaero's World Map](https://modrinth.com/mod/xaeros-world-map)
[Open Parties and Claims](https://modrinth.com/mod/open-parties-and-claims)
[Inventory Profiles Next](https://modrinth.com/mod/inventory-profiles-next)
[Inventory Sorting](https://modrinth.com/mod/inventory-sorting)
[Inventory Management](https://modrinth.com/mod/inventory-management)
[Inventory Tabs](https://modrinth.com/mod/inventory-tabs)
[Iris](https://modrinth.com/mod/iris)

**Comment by NormalFery** [comment]
They should be themed and ready to go, but you **should still test them** before doing a new release. ***Please*** _**test and check them before you do anything else**_.

**Comment by blryface** [comment]
Looks good to me, I'll *test* it when I get home
