### ISSUE TITLE
All descriptions use the same image

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/prideGUI#8]
All PrideGUI descriptions use the same image as a banner.

Legacy should have a description in an older version and a background that fits the era.

Light should have the GUI in the light theme 

Light Legacy should mix these two

## The Fix™

Legacy's background image could be a screenshot from an older iconic seed, such as pack.png or the original Panorama

Light Mode and Light Mode Legacy can be different images too, but only if you want to go through the extra effort.

**Comment by blryface** [comment]
This should be fixed before October 31st

**Comment by NormalFery** [comment]
I'll try to work on it asap

**Comment by blryface** [comment]
** **

**Comment by blryface** [comment]
This is fixed in PrideGUI's modrinth pages, and will be here soon™

**Comment by blryface** [comment]
closing as completed already because I will probably forget to close it tomorrow depending on the time I decide to sync the descriptions
